### ISSUE TITLE
gulp command freeze on bundle_js save on MacOs 10.10.4

### ISSUE THREAD

**Issue by icemanovich** [centrifugal/web#1]
![2015-08-14 13 02 42](https://cloud.githubusercontent.com/assets/4434711/9271729/daf52610-4284-11e5-9961-ed4d24553d6f.png)

**Comment by FZambia** [comment]
Hello!

This is a normal behaviour as gulp watches for file changes in this case and in case of any update in js or css files creates new bundle files

**Comment by FZambia** [comment]
If you want to just build minified versions of css and js bundles you should run:

```
gulp build
```

**Comment by icemanovich** [comment]
Yes, it works. Thanks!

**Comment by FZambia** [comment]
Welcome!
