### ISSUE TITLE
Add total of channels, clients and users in status page

### ISSUE THREAD

**Issue by edgardmessias** [centrifugal/web#17]
Add total of channels, clients and users in status page if have 2 or more nodes

**Comment by FZambia** [comment]
@edgardmessias hello, +1 to this - this would be a nice addition. Any chance that you will send pr with it?

**Comment by edgardmessias** [comment]
Yes, I can try, but exist a small difference between sum of channels/users with distinct channels/users.
Clients we only need sum

**Comment by FZambia** [comment]
Hmm, right... We can only sum clients.

**Comment by FZambia** [comment]
Maybe the best solution here is to add `Total clients: <NUM>` next to `Nodes Running: <NUM>`.

**Comment by edgardmessias** [comment]
Yes, maybe is the best solution.

To get distinct number of channels, you can call the api "channels"

**Comment by FZambia** [comment]
Channels API does not scale well (it exists mostly for debugging in development) so I suppose its better to skip this

**Comment by FZambia** [comment]
@edgardmessias released in v2.2.4 - https://github.com/centrifugal/centrifugo/releases/tag/v2.2.4

Thanks for your contribution!
