### ISSUE TITLE
Error opening menu on mobile devices

### ISSUE THREAD

**Issue by denis660** [centrifugal/web#36]
Hello.

An error occurs when calling the menu on mobile devices, the screenshot is attached

![2021-01-21_13-27-22](https://user-images.githubusercontent.com/53209140/105329982-f9280300-5bfb-11eb-860c-6c8d225e2c72.jpg)

**Comment by FZambia** [comment]
Thanks, looks like updating jQuery to 3.5.1 [can help](https://stackoverflow.com/questions/61177140/uncaught-typeerror-cannot-convert-object-to-primitive-valuezone-evergreen-js1)

**Comment by FZambia** [comment]
Fixed by 95e458763d91159525e4867f0cb35bce6f4ea0c9, will be part of Centrifugo v2.8.2
