### ISSUE TITLE
better documentation on how to run admin web interface

### ISSUE THREAD

**Issue by lmj0011** [centrifugal/web#9]
if I'm running Centrifugo with the `--web` flag. How do I get the admin web interface to show up. Is there a default port the interface is set to listen on?

Basically, I'm lost on whether I need to clone this repo into my app or not.

**Comment by FZambia** [comment]
Hello! Thanks for pointing at this - fixed in https://github.com/centrifugal/documentation/commit/0204f5285e5c9e18e5f282049ed91288eafd6852
